CREATE TABLE treasury_income_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treasury_year INTEGER NOT NULL,
    income_id BIGINT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    storage_object_name VARCHAR(700) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    extension VARCHAR(10) NOT NULL,
    size_bytes BIGINT NOT NULL,
    uploaded_by VARCHAR(150) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_income_document_object UNIQUE (storage_object_name),
    CONSTRAINT ck_income_document_size CHECK (size_bytes > 0),
    CONSTRAINT fk_income_document_income FOREIGN KEY (income_id)
        REFERENCES treasury_incomes (id) ON DELETE CASCADE
);

CREATE INDEX idx_income_document_tenant_record
    ON treasury_income_documents (treasury_year, income_id);
