ALTER TABLE about_sections ADD COLUMN icon VARCHAR(30) NOT NULL DEFAULT 'USERS';
ALTER TABLE about_sections ADD COLUMN accent_color VARCHAR(20) NOT NULL DEFAULT 'TURQUOISE';
ALTER TABLE about_sections ADD COLUMN highlighted_phrase VARCHAR(240);
ALTER TABLE about_sections ADD COLUMN featured BOOLEAN NOT NULL DEFAULT FALSE;
