ALTER TABLE user_tokens DROP CONSTRAINT IF EXISTS user_tokens_type_check;
ALTER TABLE user_tokens ADD CONSTRAINT user_tokens_type_check
    CHECK (type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'ACCOUNT_INVITATION', 'REFRESH_TOKEN'));
