CREATE TABLE alumnos
(
    alumno_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo     VARCHAR(15)  NOT NULL,
    nombre     VARCHAR(100) NOT NULL,
    curso      VARCHAR(50)  NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_alumnos_codigo UNIQUE (codigo)
);

CREATE TABLE apoderados
(
    apoderado_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo        VARCHAR(15)  NOT NULL,
    nombre        VARCHAR(50)  NOT NULL,
    email         VARCHAR(100) NOT NULL,
    telefono      VARCHAR(20)  NOT NULL,
    observaciones VARCHAR(500),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT uk_apoderados_codigo UNIQUE (codigo),
    CONSTRAINT uk_apoderados_email UNIQUE (email)
);

CREATE TABLE familias
(
    familia_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id               BIGINT       NOT NULL,
    codigo                  VARCHAR(255) NOT NULL,
    observaciones_generales VARCHAR(200),
    created_at              TIMESTAMP,
    updated_at              TIMESTAMP,
    CONSTRAINT uk_familias_alumno UNIQUE (alumno_id)
);

CREATE TABLE familia_apoderados
(
    familia_id   BIGINT      NOT NULL,
    apoderado_id BIGINT      NOT NULL,
    parentesco   VARCHAR(50) NOT NULL,
    es_principal BOOLEAN     NOT NULL,
    CONSTRAINT uk_familia_apoderado UNIQUE (familia_id, apoderado_id),
    CONSTRAINT fk_familia_apoderados_familia
        FOREIGN KEY (familia_id) REFERENCES familias (familia_id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(20)  NOT NULL,
    nombre             VARCHAR(100) NOT NULL,
    correo             VARCHAR(100) NOT NULL,
    password           VARCHAR(100) NOT NULL,
    rol                VARCHAR(10)  NOT NULL,
    enabled            BOOLEAN      NOT NULL,
    account_non_locked BOOLEAN      NOT NULL,
    email_verified_at  TIMESTAMP,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    CONSTRAINT uk_users_code UNIQUE (code),
    CONSTRAINT uk_users_correo UNIQUE (correo)
);

CREATE TABLE user_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    type       VARCHAR(30) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    used_at    TIMESTAMP,
    created_at TIMESTAMP,
    CONSTRAINT uk_user_tokens_hash UNIQUE (token_hash),
    CONSTRAINT user_tokens_type_check
        CHECK (type IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'ACCOUNT_INVITATION')),
    CONSTRAINT fk_user_token_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE annual_fee_configs
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_year        INTEGER        NOT NULL,
    annual_amount   NUMERIC(14, 0) NOT NULL,
    allowed_mode    VARCHAR(20)    NOT NULL,
    annual_due_date DATE           NOT NULL,
    first_due_date  DATE           NOT NULL,
    second_due_date DATE           NOT NULL,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NOT NULL,
    CONSTRAINT uk_annual_fee_year UNIQUE (fee_year)
);

CREATE TABLE family_fee_plans
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id  BIGINT      NOT NULL,
    family_id  BIGINT      NOT NULL,
    mode       VARCHAR(20) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL,
    CONSTRAINT uk_family_fee_plan UNIQUE (config_id, family_id),
    CONSTRAINT fk_fee_plan_config
        FOREIGN KEY (config_id) REFERENCES annual_fee_configs (id) ON DELETE CASCADE,
    CONSTRAINT fk_fee_plan_family
        FOREIGN KEY (family_id) REFERENCES familias (familia_id) ON DELETE CASCADE
);

CREATE TABLE fee_obligations
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id     BIGINT         NOT NULL,
    installment VARCHAR(20)    NOT NULL,
    concept     VARCHAR(80)    NOT NULL,
    amount      NUMERIC(14, 0) NOT NULL,
    due_date    DATE           NOT NULL,
    status      VARCHAR(20)    NOT NULL,
    created_at  TIMESTAMP      NOT NULL,
    updated_at  TIMESTAMP      NOT NULL,
    CONSTRAINT uk_fee_obligation UNIQUE (plan_id, installment),
    CONSTRAINT fk_fee_obligation_plan
        FOREIGN KEY (plan_id) REFERENCES family_fee_plans (id) ON DELETE CASCADE
);

CREATE TABLE fee_payments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    obligation_id    BIGINT         NOT NULL,
    payment_date     DATE           NOT NULL,
    amount           NUMERIC(14, 0) NOT NULL,
    registered_by    VARCHAR(150)   NOT NULL,
    observations     VARCHAR(500),
    annulled         BOOLEAN        NOT NULL,
    annulled_at      TIMESTAMP,
    annulled_by      VARCHAR(150),
    annulment_reason VARCHAR(500),
    created_at       TIMESTAMP      NOT NULL,
    CONSTRAINT fk_fee_payment_obligation
        FOREIGN KEY (obligation_id) REFERENCES fee_obligations (id) ON DELETE CASCADE
);

CREATE TABLE contribution_configs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year       INTEGER     NOT NULL,
    contribution_type VARCHAR(20) NOT NULL,
    name              VARCHAR(80) NOT NULL,
    active            BOOLEAN     NOT NULL,
    reference_amount  NUMERIC(12, 0),
    observations      VARCHAR(500),
    created_at        TIMESTAMP   NOT NULL,
    updated_at        TIMESTAMP   NOT NULL,
    CONSTRAINT uk_contribution_config_year_type
        UNIQUE (school_year, contribution_type)
);

CREATE TABLE family_contributions
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id           BIGINT      NOT NULL,
    school_year         INTEGER     NOT NULL,
    contribution_type   VARCHAR(20) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    amount              NUMERIC(12, 0),
    payment_date        DATE,
    registered_by       VARCHAR(150),
    notes               VARCHAR(500),
    cancelled_at        TIMESTAMP,
    cancelled_by        VARCHAR(150),
    cancellation_reason VARCHAR(500),
    created_at          TIMESTAMP   NOT NULL,
    updated_at          TIMESTAMP   NOT NULL,
    CONSTRAINT uk_family_contribution_year_type
        UNIQUE (family_id, school_year, contribution_type),
    CONSTRAINT fk_contribution_family
        FOREIGN KEY (family_id) REFERENCES familias (familia_id) ON DELETE CASCADE
);

CREATE TABLE treasury_settings
(
    setting_key   VARCHAR(80) PRIMARY KEY,
    setting_value VARCHAR(120) NOT NULL
);

CREATE TABLE treasury_audit
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action       VARCHAR(60)  NOT NULL,
    entity_type  VARCHAR(40)  NOT NULL,
    entity_id    VARCHAR(60)  NOT NULL,
    performed_by VARCHAR(150) NOT NULL,
    details      VARCHAR(500),
    created_at   TIMESTAMP    NOT NULL
);

CREATE TABLE treasury_expenses
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year         INTEGER        NOT NULL,
    description         VARCHAR(250)   NOT NULL,
    amount              NUMERIC(14, 0) NOT NULL,
    expense_date        DATE           NOT NULL,
    category            VARCHAR(30)    NOT NULL,
    payment_method      VARCHAR(20),
    recipient           VARCHAR(150),
    receipt_number      VARCHAR(100),
    notes               VARCHAR(1000),
    status              VARCHAR(20)    NOT NULL,
    registered_by       VARCHAR(150)   NOT NULL,
    cancelled_at        TIMESTAMP,
    cancelled_by        VARCHAR(150),
    cancellation_reason VARCHAR(500),
    created_at          TIMESTAMP      NOT NULL,
    updated_at          TIMESTAMP      NOT NULL
);

CREATE INDEX idx_expense_year_date
    ON treasury_expenses (school_year, expense_date);
CREATE INDEX idx_expense_status ON treasury_expenses (status);

CREATE TABLE treasury_incomes
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_year         INTEGER        NOT NULL,
    description         VARCHAR(250)   NOT NULL,
    amount              NUMERIC(14, 0) NOT NULL,
    income_date         DATE           NOT NULL,
    category            VARCHAR(35)    NOT NULL,
    source              VARCHAR(150),
    payment_method      VARCHAR(20),
    receipt_number      VARCHAR(100),
    course              VARCHAR(80),
    family_id           BIGINT,
    notes               VARCHAR(1000),
    status              VARCHAR(20)    NOT NULL,
    registered_by       VARCHAR(150)   NOT NULL,
    cancelled_at        TIMESTAMP,
    cancelled_by        VARCHAR(150),
    cancellation_reason VARCHAR(500),
    created_at          TIMESTAMP      NOT NULL,
    updated_at          TIMESTAMP      NOT NULL
);

CREATE INDEX idx_income_year_date
    ON treasury_incomes (school_year, income_date);
CREATE INDEX idx_income_status ON treasury_incomes (status);

CREATE TABLE school_events
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(150) NOT NULL,
    school_year            INTEGER      NOT NULL,
    event_date             DATE         NOT NULL,
    description            VARCHAR(1000),
    status                 VARCHAR(25)  NOT NULL,
    observations           VARCHAR(1000),
    gross_revenue          NUMERIC(14, 0),
    revenue_date           DATE,
    revenue_description    VARCHAR(250),
    revenue_payment_method VARCHAR(40),
    revenue_receipt        VARCHAR(100),
    revenue_notes          VARCHAR(500),
    settlement_remainder   NUMERIC(14, 0),
    settlement_confirmed   BOOLEAN      NOT NULL,
    created_at             TIMESTAMP    NOT NULL,
    updated_at             TIMESTAMP    NOT NULL,
    CONSTRAINT uk_school_event_name UNIQUE (name)
);

CREATE TABLE school_event_participants
(
    event_id           BIGINT       NOT NULL,
    course_name        VARCHAR(80)  NOT NULL,
    stand_name         VARCHAR(120) NOT NULL,
    stand_type         VARCHAR(100),
    stand_description  VARCHAR(500),
    responsible        VARCHAR(150),
    participant_notes  VARCHAR(500),
    gross_share        NUMERIC(14, 0),
    own_expenses       NUMERIC(14, 0),
    net_profit         NUMERIC(14, 0),
    transfer_status    VARCHAR(30),
    transfer_income_id BIGINT,
    CONSTRAINT uk_event_course UNIQUE (event_id, course_name),
    CONSTRAINT fk_event_participant_event
        FOREIGN KEY (event_id) REFERENCES school_events (id)
);

CREATE TABLE school_event_expenses
(
    event_id                       BIGINT         NOT NULL,
    expense_key                    VARCHAR(36)    NOT NULL,
    expense_description            VARCHAR(250)   NOT NULL,
    expense_amount                 NUMERIC(14, 0) NOT NULL,
    expense_date                   DATE           NOT NULL,
    expense_type                   VARCHAR(15)    NOT NULL,
    expense_course                 VARCHAR(80),
    expense_category               VARCHAR(80),
    expense_responsible            VARCHAR(150),
    expense_payment_method         VARCHAR(40),
    expense_receipt                VARCHAR(100),
    expense_notes                  VARCHAR(500),
    expense_deduct_from_settlement BOOLEAN,
    expense_status                 VARCHAR(15)    NOT NULL,
    expense_registered_by          VARCHAR(150)   NOT NULL,
    expense_created_at             TIMESTAMP      NOT NULL,
    expense_cancelled_at           TIMESTAMP,
    expense_cancelled_by           VARCHAR(150),
    expense_cancellation_reason    VARCHAR(500),
    CONSTRAINT uk_event_expense UNIQUE (event_id, expense_key),
    CONSTRAINT fk_event_expense_event
        FOREIGN KEY (event_id) REFERENCES school_events (id)
);

CREATE TABLE event_stands
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id          BIGINT         NOT NULL,
    name              VARCHAR(120)   NOT NULL,
    stand_date        DATE           NOT NULL,
    start_time        TIME           NOT NULL,
    end_time          TIME           NOT NULL,
    responsible       VARCHAR(150)   NOT NULL,
    initial_fund      NUMERIC(14, 2) NOT NULL,
    status            VARCHAR(20)    NOT NULL,
    debit_commission  NUMERIC(7, 4)  NOT NULL,
    credit_commission NUMERIC(7, 4)  NOT NULL,
    created_at        TIMESTAMP      NOT NULL,
    updated_at        TIMESTAMP      NOT NULL,
    version           BIGINT         NOT NULL,
    CONSTRAINT uk_event_stand_name UNIQUE (event_id, name),
    CONSTRAINT fk_event_stand_event
        FOREIGN KEY (event_id) REFERENCES school_events (id)
);

CREATE TABLE event_stand_payment_methods
(
    stand_id       BIGINT NOT NULL,
    payment_method VARCHAR(20),
    CONSTRAINT fk_stand_payment_method_stand
        FOREIGN KEY (stand_id) REFERENCES event_stands (id)
);

CREATE TABLE event_stand_products
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stand_id      BIGINT         NOT NULL,
    name          VARCHAR(120)   NOT NULL,
    category      VARCHAR(80),
    variant       VARCHAR(100),
    price         NUMERIC(14, 2) NOT NULL,
    initial_stock INTEGER,
    current_stock INTEGER,
    available     BOOLEAN        NOT NULL,
    created_at    TIMESTAMP      NOT NULL,
    updated_at    TIMESTAMP      NOT NULL,
    version       BIGINT         NOT NULL,
    CONSTRAINT uk_stand_product_variant UNIQUE (stand_id, name, variant),
    CONSTRAINT fk_stand_product_stand
        FOREIGN KEY (stand_id) REFERENCES event_stands (id)
);

CREATE TABLE event_stand_sales
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stand_id            BIGINT         NOT NULL,
    payment_method      VARCHAR(20)    NOT NULL,
    total               NUMERIC(14, 2) NOT NULL,
    amount_received     NUMERIC(14, 2),
    change_amount       NUMERIC(14, 2),
    observation         VARCHAR(500),
    registered_by       VARCHAR(150)   NOT NULL,
    sold_at             TIMESTAMP      NOT NULL,
    status              VARCHAR(20),
    cancelled_at        TIMESTAMP,
    cancelled_by        VARCHAR(150),
    cancellation_reason VARCHAR(500),
    modified_at         TIMESTAMP,
    modified_by         VARCHAR(150),
    modification_reason VARCHAR(500),
    CONSTRAINT fk_stand_sale_stand
        FOREIGN KEY (stand_id) REFERENCES event_stands (id)
);

CREATE TABLE event_stand_sale_items
(
    sale_id      BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    product_name VARCHAR(120)   NOT NULL,
    category     VARCHAR(80),
    variant      VARCHAR(100),
    quantity     INTEGER        NOT NULL,
    unit_price   NUMERIC(14, 2) NOT NULL,
    subtotal     NUMERIC(14, 2) NOT NULL,
    CONSTRAINT fk_stand_sale_item_sale
        FOREIGN KEY (sale_id) REFERENCES event_stand_sales (id)
);
