ALTER TABLE alumnos ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE alumnos ADD COLUMN genero VARCHAR(16) NOT NULL DEFAULT 'OTROS';
ALTER TABLE alumnos ADD CONSTRAINT ck_alumnos_genero
    CHECK (genero IN ('MASCULINO', 'FEMENINO', 'OTROS'));

ALTER TABLE apoderados ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE familias ADD COLUMN activo BOOLEAN NOT NULL DEFAULT TRUE;
