CREATE TABLE IF NOT EXISTS organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL,
    type VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_organizations_slug UNIQUE (slug),
    CONSTRAINT ck_organizations_type CHECK (type IN ('LEGACY', 'SCHOOL', 'COURSE'))
);

INSERT INTO organizations (name, slug, type, active, created_at, updated_at)
SELECT 'Tesorería actual', 'default', 'LEGACY', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE slug = 'default');
