ALTER TABLE users ADD CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE alumnos ADD CONSTRAINT fk_alumnos_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE apoderados ADD CONSTRAINT fk_apoderados_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE familias ADD CONSTRAINT fk_familias_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE annual_fee_configs ADD CONSTRAINT fk_annual_fee_configs_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE family_fee_plans ADD CONSTRAINT fk_family_fee_plans_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE fee_obligations ADD CONSTRAINT fk_fee_obligations_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE fee_payments ADD CONSTRAINT fk_fee_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE contribution_configs ADD CONSTRAINT fk_contribution_configs_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE family_contributions ADD CONSTRAINT fk_family_contributions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE treasury_settings ADD CONSTRAINT fk_treasury_settings_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE treasury_audit ADD CONSTRAINT fk_treasury_audit_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE treasury_expenses ADD CONSTRAINT fk_treasury_expenses_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE treasury_incomes ADD CONSTRAINT fk_treasury_incomes_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE school_events ADD CONSTRAINT fk_school_events_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE event_stands ADD CONSTRAINT fk_event_stands_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE event_stand_products ADD CONSTRAINT fk_event_stand_products_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE event_stand_sales ADD CONSTRAINT fk_event_stand_sales_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE user_notifications ADD CONSTRAINT fk_user_notifications_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE notification_replies ADD CONSTRAINT fk_notification_replies_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE about_sections ADD CONSTRAINT fk_about_sections_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE course_photos ADD CONSTRAINT fk_course_photos_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE course_board_members ADD CONSTRAINT fk_course_board_members_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE treasury_expense_documents ADD CONSTRAINT fk_treasury_expense_documents_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE treasury_income_documents ADD CONSTRAINT fk_treasury_income_documents_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE bank_account_settings ADD CONSTRAINT fk_bank_account_settings_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE payments ADD CONSTRAINT fk_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE bank_transfer_payments ADD CONSTRAINT fk_bank_transfer_payments_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;
ALTER TABLE web_push_subscriptions ADD CONSTRAINT fk_web_push_subscriptions_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) NOT VALID;

CREATE INDEX idx_users_organization ON users (organization_id);
CREATE INDEX idx_alumnos_organization ON alumnos (organization_id);
CREATE INDEX idx_apoderados_organization ON apoderados (organization_id);
CREATE INDEX idx_familias_organization ON familias (organization_id);
CREATE INDEX idx_annual_fee_configs_organization ON annual_fee_configs (organization_id);
CREATE INDEX idx_contribution_configs_organization ON contribution_configs (organization_id);
CREATE INDEX idx_treasury_expenses_organization ON treasury_expenses (organization_id);
CREATE INDEX idx_treasury_incomes_organization ON treasury_incomes (organization_id);
CREATE INDEX idx_school_events_organization ON school_events (organization_id);
CREATE INDEX idx_event_stands_organization ON event_stands (organization_id);
CREATE INDEX idx_notifications_organization ON notifications (organization_id);
CREATE INDEX idx_course_photos_organization ON course_photos (organization_id);
CREATE INDEX idx_payments_organization ON payments (organization_id);
CREATE INDEX idx_web_push_subscriptions_organization ON web_push_subscriptions (organization_id);

ALTER TABLE users VALIDATE CONSTRAINT fk_users_organization;
ALTER TABLE alumnos VALIDATE CONSTRAINT fk_alumnos_organization;
ALTER TABLE apoderados VALIDATE CONSTRAINT fk_apoderados_organization;
ALTER TABLE familias VALIDATE CONSTRAINT fk_familias_organization;
ALTER TABLE annual_fee_configs VALIDATE CONSTRAINT fk_annual_fee_configs_organization;
ALTER TABLE family_fee_plans VALIDATE CONSTRAINT fk_family_fee_plans_organization;
ALTER TABLE fee_obligations VALIDATE CONSTRAINT fk_fee_obligations_organization;
ALTER TABLE fee_payments VALIDATE CONSTRAINT fk_fee_payments_organization;
ALTER TABLE contribution_configs VALIDATE CONSTRAINT fk_contribution_configs_organization;
ALTER TABLE family_contributions VALIDATE CONSTRAINT fk_family_contributions_organization;
ALTER TABLE treasury_settings VALIDATE CONSTRAINT fk_treasury_settings_organization;
ALTER TABLE treasury_audit VALIDATE CONSTRAINT fk_treasury_audit_organization;
ALTER TABLE treasury_expenses VALIDATE CONSTRAINT fk_treasury_expenses_organization;
ALTER TABLE treasury_incomes VALIDATE CONSTRAINT fk_treasury_incomes_organization;
ALTER TABLE school_events VALIDATE CONSTRAINT fk_school_events_organization;
ALTER TABLE event_stands VALIDATE CONSTRAINT fk_event_stands_organization;
ALTER TABLE event_stand_products VALIDATE CONSTRAINT fk_event_stand_products_organization;
ALTER TABLE event_stand_sales VALIDATE CONSTRAINT fk_event_stand_sales_organization;
ALTER TABLE notifications VALIDATE CONSTRAINT fk_notifications_organization;
ALTER TABLE user_notifications VALIDATE CONSTRAINT fk_user_notifications_organization;
ALTER TABLE notification_replies VALIDATE CONSTRAINT fk_notification_replies_organization;
ALTER TABLE about_sections VALIDATE CONSTRAINT fk_about_sections_organization;
ALTER TABLE course_photos VALIDATE CONSTRAINT fk_course_photos_organization;
ALTER TABLE course_board_members VALIDATE CONSTRAINT fk_course_board_members_organization;
ALTER TABLE treasury_expense_documents VALIDATE CONSTRAINT fk_treasury_expense_documents_organization;
ALTER TABLE treasury_income_documents VALIDATE CONSTRAINT fk_treasury_income_documents_organization;
ALTER TABLE bank_account_settings VALIDATE CONSTRAINT fk_bank_account_settings_organization;
ALTER TABLE payments VALIDATE CONSTRAINT fk_payments_organization;
ALTER TABLE bank_transfer_payments VALIDATE CONSTRAINT fk_bank_transfer_payments_organization;
ALTER TABLE web_push_subscriptions VALIDATE CONSTRAINT fk_web_push_subscriptions_organization;
