CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_type_check CHECK (type IN ('INFO', 'IMPORTANT', 'URGENT')),
    CONSTRAINT fk_notifications_creator FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_notifications UNIQUE (notification_id, user_id),
    CONSTRAINT fk_user_notifications_notification FOREIGN KEY (notification_id)
        REFERENCES notifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_notifications_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notifications_created_at ON notifications (created_at DESC);
CREATE INDEX idx_user_notifications_user_read ON user_notifications (user_id, is_read);
CREATE INDEX idx_user_notifications_created_at ON user_notifications (created_at DESC);
CREATE INDEX idx_user_notifications_notification ON user_notifications (notification_id);
