CREATE TABLE notification_replies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_notification_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_replies_delivery FOREIGN KEY (user_notification_id)
        REFERENCES user_notifications (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_replies_author FOREIGN KEY (author_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_replies_delivery_created
    ON notification_replies (user_notification_id, created_at);
